# -*- coding: utf-8 -*-
"""CLUSTERING K-MEANS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DGjpFGM0TmcyTW8Bj3xzmysmBjZC9ECX

## AGREGASI
"""

import pandas as pd

# 1. Baca file Excel/CSV
# ganti 'data.xlsx' dengan nama file kamu
df = pd.read_excel("DATA-SKRIPSI-2025-FIXX.csv.xlsx")

# 2. Agregasi per produk (Nama Obat)
agg_df = df.groupby("Nama Obat").agg(
    Total_Unit_Terjual=("Jumlah", "sum"),
    Total_Penjualan=("Total", "sum"),
).reset_index()

# 3. Tampilkan hasil
print(agg_df)

# 4. Simpan ke file baru
agg_df.to_excel("hasil_agregasi.xlsx", index=False)

"""# INSTALL LIBRARY"""

# Commented out IPython magic to ensure Python compatibility.
from sklearn.cluster import KMeans
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from matplotlib import pyplot as plt
from sklearn.preprocessing import LabelEncoder
# %matplotlib inline

"""## MENAMPILKAN DATA"""

# from google.colab import drive
# drive.mount('/content/drive')

import pandas as pd


df = pd.read_csv("/content/drive/MyDrive/skripsi/Source Code/DATASET TA.csv",
                 sep=None,
                 engine='python',
                 on_bad_lines='warn',
                 encoding='utf-8-sig')

df.head()

"""# FEATURE SELECTION"""

# !pip install mlxtend
# !pip install scikit-learn

# cek nama kolom
print(df.columns)

# Pilih fitur relevan untuk analisis clustering
selected_features = ["Nama Obat", "Jumlah", "Harga", "Jenis Obat"]

# Cek apakah semua kolom ada dalam dataset
missing_columns = [col for col in selected_features if col not in df.columns]
if missing_columns:
    print(f"⚠️ Kolom berikut tidak ditemukan dalam dataset: {missing_columns}")
else:
    # Simpan hanya fitur terpilih
    df_selected = df[selected_features]
    print("✅ Feature selection berhasil. Berikut 5 data teratas:")
    print(df_selected.head())

"""# ***MODELING***"""

# --- #MODELLING ---
# menentukan nilai k optimal
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# Ambil fitur numerik dari data
X = df[["Jumlah", "Harga", "Jenis Obat"]]

# Standarisasi data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Hitung SSE untuk jumlah cluster (k)
sse = []
K_range = range(2, 11)  # K dari 2 sampai 10

for k in K_range:
    kmeans = KMeans(n_clusters=k, n_init=10, random_state=42)
    kmeans.fit(X_scaled)
    sse.append(kmeans.inertia_)

# membuat plot grafik Elbow Method
plt.figure(figsize=(8, 5))
plt.plot(K_range, sse, marker='o', linestyle='-')

# menambahkan nilai SSE di atas setiap titik
for i, txt in enumerate(sse):
    plt.text(K_range[i], sse[i], f"{txt:.2f}", ha='right', va='bottom', fontsize=10, color='red')

# menambahkan label dan judul
plt.xlabel('Jumlah Cluster (k)')
plt.ylabel('SSE (Sum of Squared Errors)')
plt.title('Metode Elbow untuk Menentukan K Optimal')

plt.show()

# Membuat DataFrame untuk menampilkan hasil dalam bentuk tabel
pengujian_k_center = pd.DataFrame({
    'Jumlah Cluster (k)': list(K_range),
    'SSE': sse
})

# Menentukan k optimal berdasarkan selisish relatif SSE
selisih_sse = np.diff(sse)
persentase_perubahan = np.abs(selisih_sse / sse[:-1]) * 100
optimal_k = K_range[np.argmax(persentase_perubahan) + 1] # k setelah perubahan terbesar

# menampilkan tabel hasil SSE
print(pengujian_k_center)
print(f"\nJumlah cluster optimal berdasarkan Elbow Method: {optimal_k}")

"""# **K- MEANS CLUSTERING**"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from scipy.spatial.distance import euclidean

# --- 1. Siapkan Data ---
# Kolom: Nama Obat, Jumlah, Harga, Jenis Obat
# Pastikan Jenis Obat sudah bertipe numerik (0 atau 1)
df['Jenis Obat'] = df['Jenis Obat'].astype(int)

# --- 2. Pilih fitur numerik untuk clustering ---
X = df[['Jumlah', 'Harga', 'Jenis Obat']].copy()

# --- 3. Normalisasi
scaler = StandardScaler()
X[['Jumlah', 'Harga', 'Jenis Obat']] = scaler.fit_transform(X[['Jumlah', 'Harga', 'Jenis Obat']])

# --- 4. Lakukan Clustering (K-Means) ---
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
df['Cluster'] = kmeans.fit_predict(X)

# --- 5. Dapatkan centroid dari setiap cluster ---
centroids = kmeans.cluster_centers_

# --- 6. Hitung jarak tiap data ke masing-masing centroid ---
for i in range(3):
    df[f'Distance_to_Centroid_{i}'] = [
        euclidean(row, centroids[i]) for row in X.to_numpy()
    ]

# --- 7. Tampilkan hasil pengelompokan ---
print("=== Data Obat dengan Cluster dan Jarak ke Centroid ===")
print(df[['Nama Obat', 'Jumlah', 'Harga', 'Jenis Obat', 'Cluster']])

# --- 8. Buat DataFrame centroid (titik pusat tiap cluster) ---
centroids_df = pd.DataFrame(
    centroids,
    columns=['Jumlah_scaled', 'Harga_scaled', 'Jenis Obat']
)
centroids_df['Cluster'] = centroids_df.index

print("\n=== Centroid tiap Cluster (dalam skala standar) ===")
print(centroids_df)

# --- 9. Simpan hasil centroid ke Excel ---
centroids_df.to_excel("centroid_cluster_obat.xlsx", index=False)

print("\n✅ Hasil centroid telah disimpan sebagai 'centroid_cluster_obat.xlsx'")

# Daftar nama dan jenis obat dalam setiap cluster
print("\nDaftar obat per cluster:")
for cluster_id in sorted(df['Cluster'].unique()):
    anggota = df[df['Cluster'] == cluster_id][['Nama Obat', 'Jenis Obat']]
    print(f"\nCluster {cluster_id} ({len(anggota)} obat):")
    for _, row in anggota.iterrows():
        print(f"- {row['Nama Obat']} (Jenis: {row['Jenis Obat']})")

"""# **VISUALISASI**"""

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# --- Visualisasi 3D Cluster dengan Centroid ---
fig = plt.figure(figsize=(8, 8))
ax = fig.add_subplot(111, projection='3d')

# Warna tiap cluster
colors = ['orange', 'green', 'red']

# Scatter 3D untuk setiap cluster
for cluster, color in zip(range(3), colors):
    data_cluster = df[df['Cluster'] == cluster]
    ax.scatter(
        data_cluster['Jumlah'],
        data_cluster['Harga'],
        data_cluster['Jenis Obat'],
        c=color, label=f'Cluster {cluster}', s=50
    )

# --- Tambahkan centroid ---
ax.scatter(
    centroids[:, 0],  # sumbu X (Jumlah)
    centroids[:, 1],  # sumbu Y (Harga)
    centroids[:, 2],  # sumbu Z (Jenis Obat)
    c='black', marker='X', s=200, label='Centroid'
)

# --- Tambahkan label teks pada tiap centroid ---
for i, (x, y, z) in enumerate(centroids):
    ax.text(x, y, z, f'C{i}', color='black', fontsize=10, weight='bold')

# Label sumbu
ax.set_xlabel('Jumlah Penjualan')
ax.set_ylabel('Harga (Rp)')
ax.set_zlabel('Jenis Obat (0=Antibiotik, 1=Non Antibiotik)')

# Judul dan legenda
ax.set_title('Visualisasi 3D Cluster Penjualan Obat dengan Centroid')
ax.legend()

plt.show()

"""# **EVALUASI DBI**"""

from sklearn.metrics import davies_bouldin_score

dbi_score = davies_bouldin_score(X_scaled, df['Cluster'])
print("Davies-Bouldin Index (DBI):", dbi_score)
